# For setting up admin host - phpMyAdmin and phpRedisAdmin
# Use networks and depends_on instead of link which is deprecated

version: '3'
services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
      args:
        version: ${NGINX_VERSION}
    environment:
     - html_volume=${HTML_VOLUME}
    ports:
     - "${NGINX_PORT}:${DOCKER_NGINX_PORT}"
    volumes:
     - ${HTML_VOLUME}:${HTML_VOLUME}
    depends_on:
     - phpmyadmin
#     - phpredisadmin
    networks:
     - backend_phpmyadmin
     - backend_phpredisadmin

  phpmyadmin:
    build:
      context: ./phpmyadmin/
      dockerfile: Dockerfile
      args:
        version: ${PHP_FPM_VERSION}
    environment:
     - PMA_HOSTS=${PMA_HOSTS}
     - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
    restart: always
    ports:
     - "9001:9000"
    volumes:
     - ${HTML_VOLUME}:${HTML_VOLUME}
     - /sessions
    depends_on:
     - phpredisadmin
    networks:
     - backend_phpmyadmin

  phpredisadmin:
    build:
      context: ./phpredisadmin/
      dockerfile: Dockerfile
      args:
        version: ${PHP_FPM_VERSION}
    restart: always
    volumes:
     - ${HTML_VOLUME}:${HTML_VOLUME}
    networks:
     - backend_phpredisadmin

networks:
  backend_phpmyadmin:
    driver: bridge
  backend_phpredisadmin:
    driver: bridge
